use python2 in shebang per pep-0394
Resolves installation failures in envs where `python`==`python3`

    In bin
    make[1]: Entering directory
    `/home/travis/build/lsst/lsstsw/sources/eups-1.5.9/bin'
    chmod u+w /home/travis/build/lsst/lsstsw/eups/1.5.9/bin
      File "./mksetup", line 37
        print "Writing a csh startup script";
    SyntaxError: Missing parentheses in call to 'print'
    make[1]: *** [install] Error 1